export default [
  {
    id: self.crypto.randomUUID(),
    name: "Make a sandwitch",
    createDate: new Date("12.12.2023"),
    category: "Thoughts",
    content: "SomeContent 12.12.2021",
    is_archived: false,
  },
  {
    id: self.crypto.randomUUID(),
    name: "Make a sandwitch",
    createDate: new Date("12.12.2023"),
    category: "Task",
    content: "SomeContent 12.12.2021",
    is_archived: false,
  },
  {
    id: self.crypto.randomUUID(),
    name: "Make a sandwitch",
    createDate: new Date("12.12.2023"),
    category: "Idea",
    content: "SomeContent 12.12.2021",
    is_archived: true,
  },
  {
    id: self.crypto.randomUUID(),
    name: "Make a sandwitch",
    createDate: new Date("12.12.2023"),
    category: "Task",
    content: "SomeContent 12.12.2021",
    is_archived: false,
  },
  {
    id: self.crypto.randomUUID(),
    name: "Make a sandwitch",
    createDate: new Date("12.12.2023"),
    category: "Quote",
    content: "SomeContent 12.12.2021",
    is_archived: true,
  },
  {
    id: self.crypto.randomUUID(),
    name: "Make a sandwitch",
    createDate: new Date("12.12.2023"),
    category: "Quote",
    content: "SomeContent 12.12.2021",
    is_archived: true,
  },
  {
    id: self.crypto.randomUUID(),
    name: "Make a sandwitch",
    createDate: new Date("12.12.2023"),
    category: "Task",
    content: "SomeContent 12.12.2021",
    is_archived: false,
  },
];
